[redhat] makefile: Add user option to fail when building dirty tree
Message-id: <1493211777-24223-1-git-send-email-prarit@redhat.com>
Patchwork-id: 177154
O-Subject: [RHEL7.4 PATCH INTERNAL v3] redhat/Makefile: Add user option to fail when building dirty tree
Bugzilla:
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Jon Masters <jcm@redhat.com>

Bugzilla: http://bugzilla.redhat.com/faildirtytree

When building a dirty git tree, the build currently warns and continues
with a three line message indicating that the tree is dirty.  This is
almost always what we don't want to happen and it is annoying when you
forget to commit your changes to the tree you are trying to build.

Modify the code so that a user can execute

git config --add [--global] rhel.faildirtytree true

to fail a 'rh-*' make command when the tree is dirty.

With a dirty tree, 'make rh-srpm' will

fail with rhel.faildirtytree true
pass with rhel.faildirtytree undefined
pass with rhel.faildirtytree false

With a clean tree, 'make rh-srpm' will pass in all cases.

Also ... add a period to the existing warning.

v2: add better description, add rh-git-dirtytree target so the build failure
occurs immediately:

[root@intel-purley-02 rhel7]# make rh-srpm
make -C redhat rh-srpm
BUILDID is ".test". Update '/home/rhel7/localversion' to change.
TEST is "None". Update '/home/rhel7/tests' to change.
make[1]: Entering directory `/home/rhel7/redhat'
Gathering new log entries since kernel-3.10.0-656.el7
ERROR: There are uncommitted changes in your tree or the changes are not
in sync with linux-kernel-test.patch. Either commit the changes or run
make rh-test-patch.
make[1]: *** [rh-git-dirtytree] Error 1
make[1]: Leaving directory `/home/rhel7/redhat'
make: *** [rh-srpm] Error 2
[root@intel-purley-02 rhel7]#
[root@intel-purley-02 rhel7]# make rh-help
<snip>
  rh-git-dirtytree  - Test to see if git tree is dirty.  Will fail if
                      git config value rhel.faildirtytree is true.

v3: cleanup superflous touch, and make "rh-git-dirtytree" consistent

Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Cc: Rafael Aquini <aquini@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Frantisek Hrbata <fhrbata@redhat.com>
Cc: dzickus@redhat.com
Cc: darcari@redhat.com

Cc: Rafael Aquini <aquini@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Frantisek Hrbata <fhrbata@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>

diff --git a/redhat/Makefile b/redhat/Makefile
--- a/redhat/Makefile
+++ b/redhat/Makefile
@@ -27,6 +27,9 @@ BUILD_TARGET ?= --scratch $(BUILD_SCRATCH_TARGET)
 RHGITURL:=$(shell git config rhg.url || git config remote.origin.pushurl || git config remote.origin.url)
 RHGITCOMMIT?=$(shell git log -1 --pretty=format:%H)
 
+FAILDIRTY:=$(shell git config rhel.faildirtytree)
+FAILDIRTYMSG="There are uncommitted changes in your tree or the changes are not in sync with linux-kernel-test.patch. Either commit the changes or run 'make rh-test-patch'."
+
 # this section is needed in order to make O= to work
 _OUTPUT := ..
 ifeq ("$(origin O)", "command line")
@@ -125,8 +128,7 @@ setup-source: rh-clean-sources
 	@$(REDHAT)/genspec.sh $(SOURCES) $(SOURCES)/$(SPECFILE) $(PKGRELEASE) $(RPMVERSION) $(RELEASED_KERNEL) $(SPECRELEASE) $(DISTRO_BUILD) $(__ZSTREAM) $(KABIDUPCHK)
 	@cp $(SOURCES)/$(SPECFILE) $(SOURCES)/../SPECS/
 
-sources-rh: $(TARBALL) rh-configs rh-kabi rh-kabi-dup
-	@cp -l $(TARBALL) $(SOURCES)/ || cp $(TARBALL) $(SOURCES)/
+rh-git-dirtytree:
 	@touch $(TESTPATCH)
 	@git diff --no-renames HEAD > $(TESTPATCH).tmp
 	@# 1) filterdiff will return crap from the patches it just filtered,
@@ -137,9 +139,18 @@ sources-rh: $(TARBALL) rh-configs rh-kabi rh-kabi-dup
 	@#    lines, which will be considered an error
 	@($(FILTERDIFF) $(TESTPATCH).tmp | egrep -v "^index|^diff" >$(TESTPATCH).tmp2; true)
 	@mv $(TESTPATCH).tmp2 $(TESTPATCH).tmp
-	@diff $(TESTPATCH).tmp $(TESTPATCH) > /dev/null || \
-		echo "WARNING: There are uncommitted changes in your tree or the changes are not in sync with linux-kernel-test.patch.  Either commit the changes or run 'make rh-test-patch'"
+	@diff $(TESTPATCH).tmp $(TESTPATCH) > /dev/null ||	\
+		(if [ "$(FAILDIRTY)" != "true" ]; then		\
+			echo "WARNING: $(FAILDIRTYMSG)";	\
+		else						\
+			echo "ERROR: $(FAILDIRTYMSG)";		\
+			rm $(TESTPATCH).tmp;			\
+			exit 1;					\
+		fi)
 	@rm $(TESTPATCH).tmp
+
+sources-rh: rh-git-dirtytree $(TARBALL) rh-configs rh-kabi rh-kabi-dup
+	@cp -l $(TARBALL) $(SOURCES)/ || cp $(TARBALL) $(SOURCES)/
 	@cp $(TESTPATCH) $(SOURCES)/linux-kernel-test.patch
 	@# if the extra_certificates doesn't exist, create a empty one
 	@(if [ ! -f keys/extra_certificates ]; then \
@@ -277,6 +288,8 @@ rh-help:
 	@echo  '  rh-cross-[ARCH]-rpm - [x86_64 only] execute rpm builds for specified'
 	@echo  '			ARCH using RHEL cross compiler'
 	@echo  '  rh-get-latest - returns latest-pkg tag from brew'
+	@echo  '  rh-git-dirtytree  - Test to see if git tree is dirty.  Will fail if'
+	@echo  '		      git config value rhel.faildirtytree is true.'
 
 	@echo  ''
 	@echo  'Configuration targets:'
